//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject10._5._2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderTbl
    {
        public int id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> prod_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
