//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject10._5._2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orderTbls = new HashSet<orderTbl>();
        }
    
        public int prod_id { get; set; }
        public string prod_name { get; set; }
        public string prod_image { get; set; }
        public string prod_description { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> Cat_ID { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTbl> orderTbls { get; set; }
    }
}
